name: fluttercovid19
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  device_preview: ^0.4.7
  responsive_widgets: ^2.0.1
  retrofit: ^1.3.4
  dio: ^3.0.9
  json_serializable: ^3.3.0
  flutter_bloc: ^6.0.1
  bloc: ^6.0.1
  equatable: ^1.2.3
  flutter_spinkit: ^4.1.2+1
  google_fonts: ^1.1.0
  frefresh: ^1.1.0
  shimmer: ^1.1.1
  flutter_vector_icons: ^0.2.1
  logger: ^0.9.1
  get_it: ^4.0.2
  carousel_pro: ^1.0.0
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  retrofit_generator: ^1.3.7+4

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
